# Generated by Django 3.2 on 2021-05-10 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('thumb', models.ImageField(null=True, upload_to='images/', verbose_name='')),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.trainer')),
            ],
        ),
    ]
