# Generated by Django 3.2 on 2021-05-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actions', '0003_auto_20210511_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorevideos',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
