# Generated by Django 3.2 on 2021-05-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actions', '0004_explorevideos_discription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explorevideos',
            name='thumb',
        ),
        migrations.AlterField(
            model_name='explorevideos',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='videos'),
        ),
    ]
