# Generated by Django 3.2 on 2021-05-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actions', '0005_auto_20210513_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explorevideos',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
