# Generated by Django 3.2 on 2021-05-28 05:08

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Actions', '0007_explorevideos_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traineeChatContent', fernet_fields.fields.EncryptedTextField()),
                ('trainerChatContent', fernet_fields.fields.EncryptedTextField()),
                ('chatRoom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Actions.chatroom')),
            ],
        ),
    ]
