# Generated by Django 3.2 on 2021-05-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actions', '0008_chatcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcontent',
            name='traineeChatContent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatcontent',
            name='trainerChatContent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
