# Generated by Django 3.2 on 2021-05-28 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Actions', '0009_auto_20210528_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatcontent',
            old_name='traineeChatContent',
            new_name='chatContentText',
        ),
        migrations.RemoveField(
            model_name='chatcontent',
            name='trainerChatContent',
        ),
        migrations.AddField(
            model_name='chatcontent',
            name='chatter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
