# Generated by Django 3.2 on 2021-05-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actions', '0010_auto_20210528_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorevideos',
            name='thumb',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
